session_name: pesterbot
start_directory: /home/maynard/workspace/pesterbot
windows:
- panes:
  - shell_command: vim -S Session.vim
- focus: 'true'
  layout: main-vertical
  panes:
  - shell_command:
    - source tokens.env
    - git status
    focus: true
  - shell_command: ngrok http -bind-tls=true 4000
